name: spigot_autobuild
on: workflow_dispatch
jobs:
  build_above_1_17_1:
    runs-on: ubuntu_latest
    strategy:
            matrix:
                ver:
                    - '1.19.2'
                    - '1.19.1'
                    - '1.19'
                    - '1.18.2'
                    - '1.18.1'
                    - '1.18'
    env:
        ver: ${{ matrix.ver }}
    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: "adopt"
          java-version: '17'
      
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
      - name: Create Output File
        run: mkdir ./above_1.17.1
      
      - name: Build Jars
        # if: ${{ matrix.ver !=  env.latest }}
        continue-on-error: true
        run: java -jar BuildTools.jar --rev $ver --output-dir ./above_1.17.1

  build_in_1_17_1-1_17:
    runs-on: ubuntu_latest
    strategy:
            matrix:
                ver:
                    - '1.17.1'
                    - '1.17'
    env:
        ver: ${{ matrix.ver }}
    steps:
      - name: Setup Java 16
        uses: actions/setup-java@v3.6.0
        with:
          distribution: "adopt"
          java-version: '16'
       
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
      - name: Create Output File
        run: mkdir ./in_1.17.1-1.17
      
      - name: Build Jars
        # if: ${{ matrix.ver !=  env.latest }}
        continue-on-error: true
        run: java -jar BuildTools.jar --rev $ver --output-dir ./in_1.17.1-1.17
  
  build_below_1_17:
    runs-on: ubuntu_latest
    strategy:
            matrix:
                ver:
                    - '1.16.5'
                    - '1.16.4'
                    - '1.16.3'
                    - '1.16.2'
                    - '1.16.1'
                    - '1.15.2'
                    - '1.15.1'
                    - '1.15'
                    - '1.14.4'
                    - '1.14.3'
                    - '1.14.2'
                    - '1.14.1'
                    - '1.14'
                    - '1.13.2'
                    - '1.13.1'
                    - '1.13'
                    - '1.12.2'
                    - '1.12.1'
                    - '1.12'
                    - '1.11.2'
                    - '1.11.1'
                    - '1.11'
                    - '1.10.2'
                    - '1.9.4'
                    - '1.9.2'
                    - '1.9'
                    - '1.8.8'
                    - '1.8.3'
                    - '1.8'
    env:
        ver: ${{ matrix.ver }}
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v3.6.0
        with:
          distribution: "adopt"
          java-version: '8'
     
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
      - name: Create Output File
        run: mkdir ./below_1.17
        
      - name: Build Jars
        # if: ${{ matrix.ver !=  env.latest }}
        continue-on-error: true
        run: java -jar BuildTools.jar --rev $ver --output-dir ./below_1.17
