name: spigot_autobuild
on: workflow_dispatch
jobs:
  build_above_1_17_1:
    runs-on: ubuntu-latest
    strategy:
            matrix:
                ver:
                    - '1.19.2'
                    - '1.19.1'
                    - '1.19'
                    - '1.18.2'
                    - '1.18.1'
                    - '1.18'
    env:
        ver: ${{ matrix.ver }}
    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: "adopt"
          java-version: '17'
      
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
      - name: Create Output File
        run: mkdir path/spigot/above_1.17.1
      
      - name: Build Jars
        continue-on-error: true
        run: java -jar BuildTools.jar --rev $ver --output-dir path/spigot/ver/above_1.17.1
        
      - name: Upload Jar Files
        uses: actions/upload-artifact@v3.1.0
        with:
          path: path/spigot/all
          
  upload_and_dist:
        needs:
            - build_above_1_17_1

        runs-on: ubuntu-latest

        steps:
            - run: mkdir spigot

            - uses: actions/download-artifact@v3.0.0
              with:
                  name: outputs
                  path: spigot/

            - run: "tree"

            - name: Upload to release
              uses: ncipollo/release-action@v1.11.1
              with:
                  name: Spigot_Release_above_1.17.1
                  allowUpdates: true
                  replacesArtifacts: true
                  tag: BuildRelease
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: spigot/*
