name: spigot_autobuild
on: workflow_dispatch
jobs:
  build_above_1_17_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ver:
          - '1.19.2'
          - '1.19.1'
          - '1.19'
          - '1.18.2'
          - '1.18.1'
          - '1.18'
    env:
        ver: ${{ matrix.ver }}
    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: "adopt"
          java-version: '17'
      
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
      - name: Make Dir Outputs
        run: mkdir ./outputs

      - name: Build Jars
        continue-on-error: true
        run: java -jar BuildTools.jar --rev $ver --output-dir ./outputs
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: outputs
          path: outputs
  
  upload_spigot_release:
    runs-on: ubuntu-latest
    needs:
      - build_above_1_17_1
    steps:
      - run: mkdir spigot_release
      
      - uses: actions/download-artifact@v3.0.0
        with:
          name: output_spigot_release
          path: spigot_release/
      
      - name: Upload to release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: Build_Spigot
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: spigot_release/*
