name: spigot_autobuild
on: workflow_dispatch
jobs:
  build_above_1_17_1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ver:
          - '1.19.2'
          - '1.19.1'
          - '1.19'
          - '1.18.2'
          - '1.18.1'
          - '1.18'
    env:
        ver: ${{ matrix.ver }}
    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: "adopt"
          java-version: '17'
      
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
      - name: Make Dir Outputs
        run: mkdir outputs

      - name: Build Jars
        continue-on-error: true
        run: java -jar BuildTools.jar --rev $ver --output-dir ./outputs
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: outputs
          path: outputs

  build_in_1_17_1-1_17:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ver:
          - '1.17.1'
          - '1.17'
    env:
        ver: ${{ matrix.ver }}
    steps:
      - name: Setup Java 16
        uses: actions/setup-java@v3.6.0
        with:
          distribution: "adopt"
          java-version: '16'
       
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
      - name: Make Dir Outputs
        run: mkdir outputs

      - name: Build Jars
        continue-on-error: true
        run: java -jar BuildTools.jar --rev $ver --output-dir ./outputs
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: outputs
          path: outputs

  build_below_1_17:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ver:
          - '1.16.5'
          - '1.16.4'
          - '1.16.3'
          - '1.16.2'
          - '1.16.1'
          - '1.16.'
          - '1.15.2'
          - '1.15.1'
          - '1.15'
          - '1.14.4'
          - '1.14.3'
          - '1.14.2'
          - '1.14.1'
          - '1.14'
          - '1.13.2'
          - '1.13.1'
          - '1.13'
          - '1.12.2'
          - '1.12.1'
          - '1.12'
          - '1.11.2'
          - '1.11.1'
          - '1.11'
          - '1.10.2'
          - '1.10.1'
          - '1.10'
          - '1.9.4'
          - '1.9.3'
          - '1.9.2'
          - '1.9.1'
          - '1.9'
          - '1.8.8'
          - '1.8.7'
          - '1.8.6'
          - '1.8.5'
          - '1.8.4'
          - '1.8.3'
          - '1.8.2'
          - '1.8.1'
          - '1.8'
          - '1.7.10'
          - '1.7.9'
          - '1.7.8'
          - '1.7.7'
          - '1.7.6'
          - '1.7.5'
          - '1.7.4'
          - '1.7.3'
          - '1.7.2'
          - '1.7.1'
          - '1.7'
          - '1.6.4'
          - '1.6.2'
          - '1.6.1'
          - '1.5.2'
          - '1.5.1'
          - '1.4.7'
          - '1.4.6'
          - '1.4.5'
          - '1.4.4'
          - '1.4.2'
          - '1.3.2'
          - '1.3.1'
    env:
        ver: ${{ matrix.ver }}
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v3.6.0
        with:
          distribution: "adopt"
          java-version: '8'
     
      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
      - name: Make Dir Outputs
        run: mkdir outputs

      - name: Build Jars
        continue-on-error: true
        run: java -jar BuildTools.jar --rev $ver --output-dir ./outputs
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: outputs
          path: outputs
          
  upload_and_dist:
        needs:
            - build_above_1_17_1
            - build_in_1_17_1-1_17
            - build_below_1_17

        runs-on: ubuntu-latest

        steps:
            - name: Make Dir Spigot
              run: mkdir spigot

            - name: Uses download-artifact to download
              uses: actions/download-artifact@v3.0.0
              with:
                  name: outputs
                  path: spigot/

            - name: Upload artifact to release
              uses: ncipollo/release-action@v1.11.1
              with:
                  name: Spigot_All_Version_Release
                  allowUpdates: true
                  replacesArtifacts: true
                  tag: BuildRelease
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: spigot/*
